---
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: true
VALIDATE_ALL_CODEBASE: false
LINTER_RULES_PATH: '.'
# linter-configs js/ts files
TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
TYPESCRIPT_DEFAULT_STYLE: prettier
PRE_COMMANDS:
  - command: yarn add eslint-plugin-github
  - cwd: "workspace"