---
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: true
VALIDATE_ALL_CODEBASE: false
DISABLE: REPOSITORY_DEVSKIM
LINTER_RULES_PATH: '.'
# linter-configs js/ts files
TYPESCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_DEFAULT_STYLE: prettier
