---
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: true
VALIDATE_ALL_CODEBASE: false
LINTER_RULES_PATH: '.'
# linter-configs js/ts files
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
JAVASCRIPT_DEFAULT_STYLE: prettier